load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'commons-codec.jar',
    maven_coords = 'commons-codec:commons-codec:jar:1.9',
    sha256 = 'ad19d2601c3abf0b946b5c3a4113e226a8c1e3305e395b90013b78dd94a723ce',
)
