load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'ddmlib.jar',
    maven_coords = 'com.android.tools.ddms:ddmlib:jar:26.2.0',
    sha256 = 'ff9b6951698a6ec005b25e5e3b5f7fe960f566131ba8fcdf713392e10cc2dd50',
)
