load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'proguard-base.jar',
    maven_coords = 'net.sf.proguard:proguard-base:jar:6.0.3',
    sha256 = '75bc89695fa66e75374ecda439b802406f0ab1d826dd386eed0a23b1f0a9d264',
)
