load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'stax-ex.jar',
    maven_coords = 'org.jvnet.staxex:stax-ex:jar:1.7.7',
    sha256 = 'a31ff7d77163c0deb09e7fee59ad35ae44c2cee2cc8552a116ccd1583d813fb4',
)
