load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'j2objc-annotations.jar',
    maven_coords = 'com.google.j2objc:j2objc-annotations:jar:1.1',
    sha256 = '40ceb7157feb263949e0f503fe5f71689333a621021aa20ce0d0acee3badaa0f',
)
