load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'classworlds.jar',
    maven_coords = 'classworlds:classworlds:jar:1.1-alpha-2',
    sha256 = '2bf4e59f3acd106fea6145a9a88fe8956509f8b9c0fdd11eb96fee757269e3f3',
)
