load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'annotations.jar',
    maven_coords = 'com.android.tools:annotations:jar:26.2.0',
    sha256 = 'af775f75168acbadb2ff61d6955e4fbeca9b1bd9f7a40b54ab7a489e30af45bb',
)

okbuck_prebuilt(
    name = 'common.jar',
    maven_coords = 'com.android.tools:common:jar:26.2.0',
    sha256 = '3e60e91bc7c7a634bbfae3522c5e0b49e8a268a2d69904bed4bd55833f8bb0c9',
)

okbuck_prebuilt(
    name = 'dvlib.jar',
    maven_coords = 'com.android.tools:dvlib:jar:26.2.0',
    sha256 = 'c4d8fac5b8432e3676256ece4e25c3e55e8ef2da4298fb060cc6086d7e2235fc',
)

okbuck_prebuilt(
    name = 'repository.jar',
    maven_coords = 'com.android.tools:repository:jar:26.2.0',
    sha256 = '9c9e320195e7e6d9bbdf9b5b0ed1d7e4da3625ad344902cb47b32c9ef8306d82',
)

okbuck_prebuilt(
    name = 'sdk-common.jar',
    maven_coords = 'com.android.tools:sdk-common:jar:26.2.0',
    sha256 = '1e32745633177b28419041d9bd182bb99b51d1a7ad3f9b1c8b5292ed799656cd',
)

okbuck_prebuilt(
    name = 'sdklib.jar',
    maven_coords = 'com.android.tools:sdklib:jar:26.2.0',
    sha256 = '08e2715f9abd3870df8e311f77ff6f3dae61193c1f6a2de78bf2e49c6ba4725a',
)
