load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'layoutlib-api.jar',
    maven_coords = 'com.android.tools.layoutlib:layoutlib-api:jar:26.2.0',
    sha256 = '5987488847729bad6a1e72cd5dcc46b68b61d8f05ef60858b87ed1d3b9bacc58',
)
