load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'commons-logging.jar',
    maven_coords = 'commons-logging:commons-logging:jar:1.2',
    sha256 = 'daddea1ea0be0f56978ab3006b8ac92834afeefbd9b7e4e6316fca57df0fa636',
)
