load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'jaxb-core.jar',
    maven_coords = 'org.glassfish.jaxb:jaxb-core:jar:2.2.11',
    sha256 = '37bcaee8ebb04362c8352a5bf6221b86967ecdab5164c696b10b9a2bb587b2aa',
)

okbuck_prebuilt(
    name = 'jaxb-runtime.jar',
    maven_coords = 'org.glassfish.jaxb:jaxb-runtime:jar:2.2.11',
    sha256 = 'a874f2351cfba8e2946be3002d10c18a6da8f21b52ba2acf52f2b85d5520ed70',
)

okbuck_prebuilt(
    name = 'txw2.jar',
    maven_coords = 'org.glassfish.jaxb:txw2:jar:2.2.11',
    sha256 = '272a3ccad45a4511351920cd2a8633c53cab8d5220c7a92954da5526bb5eafea',
)
