load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'gson.jar',
    maven_coords = 'com.google.code.gson:gson:jar:2.8.2',
    sha256 = 'b7134929f7cc7c04021ec1cc27ef63ab907e410cf0588e397b8851181eb91092',
)
