load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'xmlpull.jar',
    maven_coords = 'xmlpull:xmlpull:jar:1.1.3.1',
    sha256 = '34e08ee62116071cbb69c0ed70d15a7a5b208d62798c59f2120bb8929324cb63',
)
