load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'jaxb-api.jar',
    maven_coords = 'javax.xml.bind:jaxb-api:jar:2.2.12-b140109.1041',
    sha256 = 'b5e60cd8b7b5ff01ce4a74c5dd008f4fbd14ced3495d0b47b85cfedc182211f2',
)
