load('//.okbuck/defs:okbuck_prebuilt.bzl', 'okbuck_prebuilt')

okbuck_prebuilt(
    name = 'multidex-instrumentation.aar',
    maven_coords = 'androidx.multidex:multidex-instrumentation:aar:2.0.0',
    sha256 = 'fb8115694b1731c23c1bbb628f5baaee37a8f3b50d69a7733b55278e101e1488',
)

okbuck_prebuilt(
    name = 'multidex.aar',
    maven_coords = 'androidx.multidex:multidex:aar:2.0.0',
    sha256 = 'c01700091072e0ff5d8ec2d00eac6b8f96ea18646080425e9ce3c6a7b5f66e33',
)
